
console.log('layout');
import localFont from "next/font/local";
import "./globals.css";
import ToastManager from "@/components/ToastManager";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  console.log("RootLayout rendered"); // 新增日志
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ToastManager>
          {children} {/* 包裹所有的子組件 */}
        </ToastManager>
      </body>
    </html>
  );
}
